description: 'ResNet ImageNet'
output_dir: $SCRATCH/sc18-dl-tutorial/imagenet-resnet-N${SLURM_JOB_NUM_NODES}-${SLURM_JOB_ID}

data:
    name: imagenet
    train_dir: /data0/ImageNet-100/train
    valid_dir: /data0/ImageNet-100/validation

model:
    name: resnet50
    input_shape: [224, 224, 3]
    n_classes: 100

optimizer:
    name: SGD
    lr: 0.0125
    momentum: 0.9

training:
    batch_size: 32
    n_epochs: 32
    lr_warmup_epochs: 5
    loss: categorical_crossentropy
    metrics: [accuracy, top_k_categorical_accuracy]
